jwt:
  issuer: jeongminchoi1017@gmail.com
  secret: wEaFDu7G7E4P7JqjbvWxtUrUaHkEAR44
logging:
  file:
    name: log/Rmsoft.log
  level:
    jdbc:
      connection: info
      resultsettable: info
      sqlonly: info
      sqltiming: info
    org:
      hibernate: info
      springframework:
        security: info
    root: info
server:
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Rmsoft123@
    url: jdbc:mysql://43.200.181.70:3306/Rmsoft
    username: rmsoft
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
  security:
    user:
      name: user
      password: 1234
  thymeleaf:
    cache: false
    # prefix 설정을 안하면 HTML 수정 후 브라우저에서 새로고침 반영 안됨
    # 그리고 반드시 classpath 경로로 쓰고 templates 마지막에 슬래쉬 (/) 붙이면 배포파일 실행 안됨
    # /를 붙여야 되는 경우는 controller 에서 return 되는 주소 값에 /가 있으면 빼야하고, /가 없으면 넣어줘야함
    # 예시) return "user/login"이면 넣어주기. "/user/login";이면 빼주기
    prefix: classpath:/templates
    mvc:
      static-path-pattern: "/static/**"
  servlet:
    multipart:
      location: src/main/resources/static/file/
      max-file-size: 10MB
mybatis:
  mapper-locations: classpath:mappers/**/*.xml